import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";

interface IRootLayout {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }: IRootLayout) {
  const locale = useLocale();

  // final step
  if (params.locale !== locale) {
    notFound();
  }

  // final step
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
